// <auto-generated />
using System;
using Lime_Editor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lime_Editor.Migrations
{
    [DbContext(typeof(LimeEditorContext))]
    partial class LimeEditorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lime_Editor.Models.Site", b =>
                {
                    b.Property<int?>("IdSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Site");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdSite"));

                    b.Property<string>("Folder")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("Template_Id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("IdSite")
                        .HasName("PK__Sites__A2DC903C1CED58AB");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Lime_Editor.Models.Template", b =>
                {
                    b.Property<int?>("IdTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Template");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdTemplate"));

                    b.Property<string>("FolderPreview")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Folder_Preview");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("Type_Id");

                    b.HasKey("IdTemplate")
                        .HasName("PK__Template__8F91BE5EDFE8DD90");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Lime_Editor.Models.TypeTemplate", b =>
                {
                    b.Property<int?>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdType"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdType")
                        .HasName("PK__Type_Tem__1A20A3D5996588A6");

                    b.ToTable("Type_Templates", (string)null);
                });

            modelBuilder.Entity("Lime_Editor.Models.User", b =>
                {
                    b.Property<int?>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_User");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUser")
                        .HasName("PK__User__D03DEDCB15E5FBBC");

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
